### ISSUE TITLE
YapDatabase+SQLCipher doesn't compile using CocoaPods 1.0.0

### ISSUE THREAD

**Issue by jmnavarro** [yapstudios/YapDatabase#322]
If you upgrade to CocoaPods 1.0.0 and try to compile a simple project using YapDatabase+SQLCipher, you get weird errors compiling `yap_vfs_shm.c`:

```
While building module 'SQLCipher' imported from /Users/jm/Desktop/TESTO/Pods/YapDatabase/YapDatabase/Internal/yap_vfs_shim.h:8:
While building module 'UIKit' imported from /Users/jm/Desktop/TESTO/Pods/Target Support Files/SQLCipher/SQLCipher-umbrella.h:1:
While building module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIAccelerometer.h:8:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:436:1: error: expected identifier or '('
@class NSString, Protocol;
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:438:19: error: unknown type name 'NSString'
FOUNDATION_EXPORT NSString *NSStringFromSelector(SEL aSelector);
                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:439:44: error: unknown type name 'NSString'
FOUNDATION_EXPORT SEL NSSelectorFromString(NSString *aSelectorName);
                                           ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:441:19: error: unknown type name 'NSString'
FOUNDATION_EXPORT NSString *NSStringFromClass(Class aClass);
                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:442:54: error: unknown type name 'NSString'
FOUNDATION_EXPORT Class __nullable NSClassFromString(NSString *aClassName);
                                                     ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:444:19: error: unknown type name 'NSString'
FOUNDATION_EXPORT NSString *NSStringFromProtocol(Protocol *proto) NS_AVAILABLE(10_5, 2_0);
                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:444:50: error: declaration of 'Protocol' must be imported from module 'ObjectiveC.runtime' before it is required
FOUNDATION_EXPORT NSString *NSStringFromProtocol(Protocol *proto) NS_AVAILABLE(10_5, 2_0);

... more errors
```

I tried with both ObjC and Swift projects and both fail. Same project, using Cocoapods 0.39.0 works

To reproduce, just create an empty project, and use the following `Podfile`:

```
platform :ios, '8.0'
use_frameworks!

target "MyTestProject" do
    pod 'YapDatabase/SQLCipher'
end
```

**Comment by robbiehanson** [comment]
```
While building module 'SQLCipher' imported from ... yap_vfs_shim.h:8:
While building module 'UIKit' imported from ... SQLCipher-umbrella.h:1:
While building module 'Foundation' imported from ... UIAccelerometer.h:8:
```

The problem seems to be that yap_vfs_shim.c/h is straight C. No Objective-C at all. But it is including sqlite (SQLCipher in this case), and the generated SQLCipher-umbrella.h file is improperly importing Objective-C. And this is causing the compiler to freak out.

It looks like CocoaPods 1.0.0 is generating "SQLCipher-umbrella.h", which is doing this:
```objective-c
#import <UIKit/UIKit.h>
``` 

I believe the [proper solution](http://stackoverflow.com/questions/5983103/adding-an-empty-c-file-to-xcode-cocoa-project-causes-thousands-of-errors/5983144#5983144) is for CocoaPods to wrap their imports based on the language:
```objective-c
#ifdef __OBJC__
#import <UIKit/UIKit.h>
#endif
```

As a temporary hack/workaround, you could try renaming the file:
yap_vfs_shim.c -> yap_vfs_shim.m

Although this really needs to be fixed in CocoaPods (if this is indeed the issue), or it will just keep on [breaking builds](https://github.com/ChatSecure/ChatSecure-iOS/issues/428) for people.

Let us know what you find. Some Googling shows you're not the only one running into this issue with CocoaPods.

**Comment by jmnavarro** [comment]
As a workaround, we're using Cocoapods 0.39.x which works as expected

**Comment by robbiehanson** [comment]
Since this hasn't been fixed in CocoaPods v1 yet, I went ahead and renamed it:
yap_vfs_shim.c -> yap_vfs_shim.m
