### ISSUE TITLE
build with carthage

### ISSUE THREAD

**Issue by prinsun** [yapstudios/YapDatabase#192]
when i using carthage, there was no macos scheme in `YapDatabase.xcodeproj`, can you add it to your todo list, please? (_sorry. my english, perhaps, is coarse_)

**Comment by natan** [comment]
+1 I'd appreciate Carthage support.

**Comment by xtazz** [comment]
+1

**Comment by raw1z** [comment]
+1

**Comment by robbiehanson** [comment]
I've started working on Carthage support. Please see the "carthage" branch.

Currently I'm seeing errors concerning the modulemap...

**Comment by robbiehanson** [comment]
Carthage support has been merged into the master branch, and should be available in 2.7.4.

Let me know if you experience any problems.

**Comment by pnicholls** [comment]
Thanks for all the effort on this and the project @robbiehanson!

Tried to install with carthage:
```
github "yapstudios/YapDatabase" "2.7.4"
```

```
$ carthage update --platform iOS
```

```
The following build commands failed:
	CompileC /Users/Pete/Library/Developer/Xcode/DerivedData/YapDatabase-ctnjhldnuoiqakgrbljsjpjpcmyt/Build/Intermediates/YapDatabase.build/Release-iphonesimulator/YapDatabase-iOS.build/Objects-normal/i386/YapDatabaseFullTextSearchHandler.o YapDatabase/Extensions/FullTextSearch/YapDatabaseFullTextSearchHandler.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
/Users/Pete/Apps/nudge/nudge-ios/Carthage/Checkouts/YapDatabase/YapDatabase/Extensions/FullTextSearch/Internal/YapDatabaseFullTextSearchPrivate.h:10:9: fatal error: 'YapMutationStack.h' file not found
/Users/Pete/Apps/nudge/nudge-ios/Carthage/Checkouts/YapDatabase/YapDatabase/Internal/YapDatabasePrivate.h:12:9: fatal error: 'YapMutationStack.h' file not found
/Users/Pete/Apps/nudge/nudge-ios/Carthage/Checkouts/YapDatabase/YapDatabase/Extensions/SecondaryIndex/Internal/YapDatabaseSecondaryIndexPrivate.h:12:9: fatal error: 'YapMutationStack.h' file not found
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/Pete/Library/Developer/Xcode/DerivedData/YapDatabase-ctnjhldnuoiqakgrbljsjpjpcmyt/Build/Intermediates/YapDatabase.build/Release-iphonesimulator/YapDatabase-iOS.build/Objects-normal/i386/YapDatabaseFullTextSearchHandler.o YapDatabase/Extensions/FullTextSearch/YapDatabaseFullTextSearchHandler.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

Could well be that I am doing something wrong.

**Comment by robbiehanson** [comment]
Oops. Forgot about the project changes on the master branch, which broke the framework target after the merge. Try now.

Note: You'll need to change from this:
```
github "yapstudios/YapDatabase" "2.7.4"
```
To one of these:
```
github "yapstudios/YapDatabase" "master"
github "yapstudios/YapDatabase" "e1f1392e63ab4ceb9a8c7f41bc3be7de3bb83980"
```

**Comment by pnicholls** [comment]
thanks again @robbiehanson, seem to build fine. 

I did get a:
```
Use of undeclared type YapDatabaseViewTransaction
```

but that could just be my project is configured incorrectly or has fallen behind. Ill find out.

**Comment by robbiehanson** [comment]
It may be how I broke up all the extensions into their own submodule. So for any extension you're using in your project, you'll need to explicitly import it:
```
@import YapDatabase; // gives you the core database & utilities
@import YapDatabase.YapDatabaseView; // just the view extension
```

**Comment by pnicholls** [comment]
Yup that was it, thanks!

**Comment by danthorpe** [comment]
Hi @robbiehanson! Thanks for all your work with the recent improvements to YapDatabase including Carthage support!

One minor suggestion however, after I stumbled across this after returning to one of my projects which uses YapDatabase which now fails to compile after updating from 2.7.2 to 2.7.4. I think the explicit modules is a pretty significant breaking change for a minor point release. It might help people if it is called out in the release notes of 2.7.4.

**Comment by robbiehanson** [comment]
> I think the explicit modules is a pretty significant breaking change for a minor point release. It might help people if it is called out in the release notes of 2.7.4.

Good point. Done: https://github.com/yapstudios/YapDatabase/wiki/Changelog

**Comment by degterev** [comment]
Hi @robbiehanson! Can you add scheme with SQLCipher support to the project?

**Comment by robbiehanson** [comment]
> Can you add scheme with SQLCipher support to the project?

This may not be possible (due to lack of support in Carthage):
https://github.com/Carthage/Carthage/issues/728

My (rudimentary) understanding is that Carthage is trying hard to position itself as the "simple" alternative to CocoaPods. So while CocoaPods has all the bells and whistles, the Carthage project is actively resisting anything that could be considered "extraneous" beyond basic use cases.

This is going to have an impact on libraries such as YapDatabase. To explain what I mean, take a look at the updated podspec for YapDatabase in the coming v2.8 branch:
https://github.com/yapstudios/YapDatabase/blob/v2.8/YapDatabase.podspec

In addition to the usual "Standard" vs "SQLCipher" flavors, I've also split it up in such a manner that allows you to pick-and-choose which extensions you might want in your project. As the YapDatabase project continues to grow, certain extensions may become unwanted. For example, the YapDatabaseCloudKit extension requires Apple's CloudKit framework. So, if you're not using it, you may not want that extension in your application. And going forward, I have other extensions which might have other dependencies such as Reachability, AFNetworking, etc. So this will become even more important in the future.
